package com.curry.note.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.curry.note.bean.bmob.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Void> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property HeadPortraitUrl = new Property(0, String.class, "headPortraitUrl", false, "HEAD_PORTRAIT_URL");
        public final static Property QQId = new Property(1, String.class, "QQId", false, "QQID");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"HEAD_PORTRAIT_URL\" TEXT," + // 0: headPortraitUrl
                "\"QQID\" TEXT);"); // 1: QQId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        String headPortraitUrl = entity.getHeadPortraitUrl();
        if (headPortraitUrl != null) {
            stmt.bindString(1, headPortraitUrl);
        }
 
        String QQId = entity.getQQId();
        if (QQId != null) {
            stmt.bindString(2, QQId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        String headPortraitUrl = entity.getHeadPortraitUrl();
        if (headPortraitUrl != null) {
            stmt.bindString(1, headPortraitUrl);
        }
 
        String QQId = entity.getQQId();
        if (QQId != null) {
            stmt.bindString(2, QQId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // headPortraitUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // QQId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setHeadPortraitUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setQQId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(User entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(User entity) {
        return null;
    }

    @Override
    public boolean hasKey(User entity) {
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
