package com.yodoo.android.baseutil.keys;

/**
 * Created by lib on 2017/11/6.
 */

public interface IntentKey {
    String TITLE = "TITLE";
    String MESSAGE = "MESSAGE";
    String MAINTABACTIVITY = "MAINTABACTIVITY";
    String LOADMOREFACTORY = "LOADMOREFACTORY";
//    String INTENTSEARCHFACTORY = "INTENTSEARCHFACTORY";
    String INTENTSEARCH = "INTENTSEARCH";
    String INTENTSEARCHRUSULT = "INTENTSEARCHRUSULT";
    String INTENTSTRCONTENT = "INTENTSTRCONTENT";
    String INTENTRELATEEXPENSE = "INTENTRELATEEXPENSE";
}
